feat(core): Support Podman and Docker, cleanup cloudctl script

diff --git a/cloudctl b/cloudctl
--- a/cloudctl
+++ b/cloudctl
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
 
-set -o errexit
 set -o nounset
 set -o pipefail
 # set -o xtrace
@@ -11,13 +10,22 @@ __file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
 __base="$(basename ${__file} .sh)"
 __bin="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
-# Set variables
+# http://www.tldp.org/LDP/abs/html/exitcodes.html
+# User-defined exit codes range 64 - 113 (in addition to 0, for success)
+readonly SUCCESS=0
+readonly E_NOT_ENOUGH_PRIVILEGES=113
+
+# Constant variables
+readonly PODMAN_CLI='podman'
+readonly DOCKER_CLI='docker'
+
+# Variables
 build=false
 force=false
 exec=false
 unset start
-container_alias='podman'
-docker_name='docker'
+is_sudo=false
+CONTAINER_ALIAS=${CONTAINER_ALIAS:-${PODMAN_CLI}}
 
 # https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash/39398359#39398359
 # As long as there is at least one more argument, keep looping
@@ -34,7 +42,7 @@ while [[ $# -gt 0 ]]; do
         ;;
         # This is a flag type option. Will catch either -d or --docker
         -d|--docker)
-        container_alias="${docker_name}"
+        CONTAINER_ALIAS="${DOCKER_CLI}"
         ;;
         # This is an arg value type option. Will catch -e value or --exec value
         -e|--exec)
@@ -49,8 +57,8 @@ while [[ $# -gt 0 ]]; do
         command="${key#*=}"
         ;;
         *)
-        # Do whatever you want with extra options
-        echo "Unknown option '${key}'"
+        # Do whatever you want with extra arguments
+        echo "Unknown argument '${key}'"
         ;;
     esac
     shift
@@ -68,42 +76,16 @@ export CLOUDBOX_VERSION='0.2.3'
 VOLUME_NAME=${CLOUDBOX_USER}'_home'
 DOCKER_TAG='local'/${CLOUDBOX_NAME}:${CLOUDBOX_VERSION}
 
-# Set local environment
-if [ $UID -ne 0 ]; then
-    LOCAL_HOME=${HOME}
-else
-    LOCAL_HOME="$(getent passwd ${SUDO_USER} | cut -d: -f6)"
-fi
-LOCAL_SSH="${LOCAL_HOME}/.ssh"
-LOCAL_WORKDIR="${LOCAL_HOME}/Projects"
-
-# Script prerequisites
-if  [ "${container_alias}" = "${docker_name}" ]; then
-    user_in_docker=$(id --name --groups --zero "${USER:-${USERNAME:-${LOGNAME}}}" | grep -c --null-data --line-regexp --fixed-strings "${docker_name}" || [[ $? == 1 ]])
-    if [ ${UID} -ne 0 ] && ! [ "${user_in_docker}" = "1" ]; then
-        echo "use: sudo ${0##*/}"
-        exit -1
-    fi
-fi
-
-if [ "${exec:-}" = "true" ]; then
-    if ${container_alias} start ${CLOUDBOX_NAME} 2>/dev/null; then
-        start=false
-    else
-        start=true
-    fi
-fi
-
-# functions
+# Functions
 
 local_workdirs () {
     # Create local working directories and files
-    if  [ "${container_alias}" = "${docker_name}" ]; then
-        sudo -H -u ${SUDO_USER} mkdir -p ${LOCAL_WORKDIR}
-        sudo -H -u ${SUDO_USER} mkdir -p ${LOCAL_SSH}
-    else
+    if  [ "${is_sudo:-}" = "false" ]; then
         mkdir -p ${LOCAL_WORKDIR}
         mkdir -p ${LOCAL_SSH}
+    else
+        sudo -H -u ${SUDO_USER} mkdir -p ${LOCAL_WORKDIR}
+        sudo -H -u ${SUDO_USER} mkdir -p ${LOCAL_SSH}
     fi
 }
 
@@ -111,8 +93,11 @@ container_build () {
     # Build cloudbox image
     local args
     pushd ${__dir}
-    args=('--layers'
-        '--force-rm=true'
+    args=''
+    if  [ "${CONTAINER_ALIAS}" = "${PODMAN_CLI}" ]; then
+        args+=('--layers')
+    fi
+    args+=('--force-rm=true'
         '--rm=true'
         "--build-arg=\"CLOUDBOX_USER=${CLOUDBOX_USER}\""
         "--build-arg=\"CLOUDBOX_SSH=${CLOUDBOX_SSH}\""
@@ -123,7 +108,7 @@ container_build () {
         "--build-arg=\"BUILD_DATE=$(date --utc +\"%FT%TZ\")\"")
     [ "${force:-}" = "true" ] && args+=('--no-cache')
     args+=("--tag='"${DOCKER_TAG}"'" '.')
-    eval ${container_alias} build ${args[@]}
+    eval ${CONTAINER_ALIAS} build ${args[@]}
     popd
 }
 
@@ -137,12 +122,17 @@ container_run () {
     fi
 
     local suffix=`cat /dev/urandom | tr -cd 'a-f0-9' | head -c 3`
-    args+=("--hostname ${container_alias}-${suffix}")
+    args+=("--hostname ${CONTAINER_ALIAS}-${suffix}")
 
-    args+=("--mount type=bind,source=\"${LOCAL_SSH}\",target=\"${CLOUDBOX_HOST_SSH}\",relabel=shared,ro=true"
-        "--mount type=bind,source=\"${LOCAL_WORKDIR}\",target=\"${CLOUDBOX_WORKDIR}\",relabel=shared"
-        "--mount type=volume,source=\"${VOLUME_NAME}\",target=\"${CLOUDBOX_HOME}\"")
-    args+=('--userns=keep-id')
+    if  [ "${CONTAINER_ALIAS}" = "${DOCKER_CLI}" ]; then
+        args+=("--mount type=bind,source=\"${LOCAL_SSH}\",target=\"${CLOUDBOX_HOST_SSH}\",ro=true"
+            "--mount type=bind,source=\"${LOCAL_WORKDIR}\",target=\"${CLOUDBOX_WORKDIR}\"")
+    else
+        args+=("--mount type=bind,source=\"${LOCAL_SSH}\",target=\"${CLOUDBOX_HOST_SSH}\",relabel=shared,ro=true"
+            "--mount type=bind,source=\"${LOCAL_WORKDIR}\",target=\"${CLOUDBOX_WORKDIR}\",relabel=shared"
+            '--userns=keep-id')
+    fi
+    args+=("--mount type=volume,source=\"${VOLUME_NAME}\",target=\"${CLOUDBOX_HOME}\"")
 
     if [ "${PWD:0:${#LOCAL_WORKDIR}}" = "${LOCAL_WORKDIR}" ]; then
         subfolder=${PWD#${LOCAL_WORKDIR}/}
@@ -158,7 +148,7 @@ container_run () {
         args+=("${DOCKER_TAG}" '/bin/bash')
     fi
 
-    eval ${container_alias} run ${args[@]}
+    eval ${CONTAINER_ALIAS} run ${args[@]}
 }
 
 container_exec () {
@@ -166,11 +156,44 @@ container_exec () {
     args=('--interactive' '--tty')
     args+=("${CLOUDBOX_NAME}" "${command}")
 
-    eval ${container_alias} exec ${args[@]}
+    eval ${CONTAINER_ALIAS} exec ${args[@]}
 }
 
+# Script prerequisites
 
-# main script
+# Check privileges
+if [ $UID -eq 0 ]; then
+    is_sudo=true
+fi
+
+if  [ "${CONTAINER_ALIAS}" = "${DOCKER_CLI}" ]; then
+    user_in_docker=$(id --name --groups --zero "${USER:-${USERNAME:-${LOGNAME}}}" | grep -c --null-data --line-regexp --fixed-strings "${DOCKER_CLI}" || [[ $? == 1 ]])
+    if ! ([ "${is_sudo:-}" = "true" ] || [ "${user_in_docker}" = "1" ]); then
+        echo "use: sudo ${0##*/}"
+        exit ${E_NOT_ENOUGH_PRIVILEGES}
+    fi
+fi
+
+# Set local environment
+if [ "${is_sudo:-}" = "false" ]; then
+    LOCAL_HOME=${HOME}
+else
+    LOCAL_HOME="$(getent passwd ${SUDO_USER} | cut -d: -f6)"
+fi
+LOCAL_SSH="${LOCAL_HOME}/.ssh"
+LOCAL_WORKDIR="${LOCAL_HOME}/Projects"
+
+# Check for running container
+if [ "${exec:-}" = "true" ]; then
+    if ${CONTAINER_ALIAS} start ${CLOUDBOX_NAME} 2>/dev/null; then
+        start=false
+    else
+        start=true
+    fi
+fi
+
+# Script main
+
 if [ "${start:-}" != "false" ]; then
     local_workdirs
 fi
